// app/dashboard/analytics/page.tsx
'use client'

import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  CardDescription,
  CardFooter,
} from '@/components/ui/card';
import { BarChart, LineChart, MessageSquare } from 'lucide-react';
import { Badge } from '@/components/ui/badge';

// Placeholder for a simple chart component (e.g., using Recharts or Tremor)
const AnalyticsChart = ({ title }: { title: string }) => (
  <div className="h-[200px] w-full flex items-center justify-center bg-zinc-100 dark:bg-zinc-800 rounded-lg border border-dashed text-zinc-500 dark:text-zinc-400">
    <LineChart className="w-6 h-6 mr-2" />
    <p>{title} (Chart Placeholder)</p>
  </div>
);

export default function AnalyticsDashboardPage() {
  // 1. **Data Fetching**:
  //    - Fetch real-time analytics data and the AI summary (e.g., /api/analytics).
  const aiSummaryText = "The past week has seen a **15% increase** in user sign-ups, primarily from the mobile platform. Conversion rates, however, dipped slightly in the checkout funnel, indicating a need for optimization on the payment page.";

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-3xl font-bold tracking-tight">Analytics Dashboard</h1>
      
      {/* AI Summary Card */}
      <Card className="border-l-4 border-zinc-500 bg-zinc-50 dark:bg-zinc-900">
        <CardHeader>
          <CardTitle className="flex items-center">
            <MessageSquare className="w-5 h-5 mr-2 text-zinc-500" />
            AI-Based Summary
            <Badge variant="secondary" className="ml-3 bg-zinc-200 dark:bg-zinc-700 text-zinc-800 dark:text-zinc-200">
              New Insight
            </Badge>
          </CardTitle>
          <CardDescription>Key insights generated by the system's AI model.</CardDescription>
        </CardHeader>
        <CardContent>
          <p className="text-sm" dangerouslySetInnerHTML={{ __html: aiSummaryText.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') }} />
        </CardContent>
      </Card>

      {/* Metrics Grid */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <MetricCard title="Total Users" value="1,245" change="+5.2% since last month" />
        <MetricCard title="Revenue" value="$45,231" change="+8.1% since last month" />
        <MetricCard title="New Signups" value="230" change="+15% since last week" />
        <MetricCard title="Bounce Rate" value="3.5%" change="-1.2% since last month" />
      </div>

      {/* Charts Section */}
      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>User Activity Over Time</CardTitle>
          </CardHeader>
          <CardContent>
            <AnalyticsChart title="Line Chart" />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Revenue by Source</CardTitle>
          </CardHeader>
          <CardContent>
            <AnalyticsChart title="Bar Chart" />
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// Reusable Metric Card Component
function MetricCard({ title, value, change }: { title: string, value: string, change: string }) {
  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle className="text-sm font-medium">{title}</CardTitle>
        <BarChart className="h-4 w-4 text-muted-foreground" />
      </CardHeader>
      <CardContent>
        <div className="text-2xl font-bold">{value}</div>
        <p className="text-xs text-muted-foreground">{change}</p>
      </CardContent>
    </Card>
  );
}